name: GitHub Actions Demo
on: [push]
jobs:
  test:
    name: "Test foo"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./foo
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.16.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.1
    - run: yarn install
    - run: yarn test
      